Changed Verbiage
emergency-food-pantry/Food-Pantry-Check-In pull request #236
Opened 2021-01-26 15:34 UTC by typer177

[EFP-16](https://codelation.atlassian.net/browse/EFP-16)

2021-01-29 17:24 UTC, t-whitney requested changes

2021-01-29 17:24 UTC, t-whitney commented on src/components/CheckIn/CheckIn.js
> +                        <p><i>Check all that are true</i></p>
Quick fix on a few of the checkboxes in this form. The another person picking up, walking home and birthday labels do not match up with the checkboxes. The result is that clicking the label does not select the box - the final two checkboxes in this form are correct, so clicking the label works as expected. It's an easy fix - just make sure the htmlFor values match up with the checkbox id

2021-02-02 17:11 UTC, typer177 commented on src/components/CheckIn/CheckIn.js
> +                        <p><i>Check all that are true</i></p>
Changed

2021-02-02 20:10 UTC, t-whitney approved these changes

2021-02-03 22:29 UTC, merged