Efp 17 user change password
emergency-food-pantry/Food-Pantry-Check-In pull request #237
Opened 2021-02-02 16:08 UTC by typer177

2021-02-02 21:36 UTC, t-whitney requested changes
- If I add an email that doesn't exist in the forgot password email field, I'm taken back to the login page without any indication of what happened. It would be useful to have an error message in this case.
- There should also be some sort of instructions for successfully sending the reset email. Right now it's really unclear what to do once you click reset (unless you get an email notification, but I don't think we should rely on that)

2021-02-03 21:50 UTC, typer177 commented on src/components/ForgotPage/ResetPage.js
> +        console.log(this.props)
cleaned up

2021-02-03 22:28 UTC, typer177 commented
>     * If I add an email that doesn't exist in the forgot password email field, I'm taken back to the login page without any indication of what happened. It would be useful to have an error message in this case.
> 
>     * There should also be some sort of instructions for successfully sending the reset email. Right now it's really unclear what to do once you click reset (unless you get an email notification, but I don't think we should rely on that)

I made one notification that will be displayed in both cases (one message to prevent info leakage)

2021-02-04 19:49 UTC, t-whitney approved these changes
- My only comment is that you could have separate messages for success and failure. Otherwise this looks good

2021-02-05 15:09 UTC, merged